### ISSUE TITLE
How to specify background color for blocks

### ISSUE THREAD

**Issue by Cutuchiqueno** [vivien/i3blocks#106]
Is there any possibility to also specify the background color of a block?

I tried to echo escape sequences but it causes an error.

**Comment by vivien** [comment]
With the i3blocks' master branch, you can specify the background of the text like this with the Pango arkup:
```` ini
[test]
full_text=<span background="red" foreground="white">Salut</span>
markup=pango
````
*Note: you need a Pango font in your i3 config, like: `font pango:Fira Mono, Icons 10`.*

Otherwise, coloring the background of the block itself is not supported by i3bar. You'll need @Airblader's i3 [Gaps fork](https://github.com/Airblader/i3).

**Comment by Cutuchiqueno** [comment]
Thank you. That is a very helpful answer. In fact, I use pango. (Thank you also for the great work on i3blocks)

**Comment by shibumi** [comment]
@vivien is there any way to set  the background color via script? The problem is I want to change the background color on a specific state. For example when my battery gets low i want to color the full battery segment background red. Is this possible? I tried using that pango markup commands inside of the shellscript. But it doesn't seem to work. Any idea?

**Comment by Airblader** [comment]
@kb100 That's not correct (anymore). While i3 does not yet allow the flexibility regarding borders on status blocks like i3-gaps, setting the background dynamically for status blocks does work by now.

However, i3blocks does not allow defining a background color it will transmit from the script (yet). One workaround, if it's a specific color, is to just use the same block twice and make sure exactly one of them outputs an empty full_text.

> However, specifically for red, having a block exit with exit code 33 (the ascii value of !), will set the whole background red.

That's not so much specifically for red, but specifically for whatever you configured i3bar to use as the urgent color.

**Comment by shibumi** [comment]
@Airblader that is not correct. I managed to set the background color via pango markups from a script. This snippet works pretty well for me:
```
echo -e "<span color='black' bgcolor='#01A252'> : $RAM_USAGE / $RAM_CAPACITY</span>\n"
```

You can set the bgcolor and color (for foreground) via shell variables, too.  The only disadvantage of using pango markup is the size of the borders. The background color has only the size of the font. So the bar looks a little bit odd...

**Comment by Airblader** [comment]
What is not correct? Where are you talking about anything of what I have said? A pango background is not the same as the background color of the status block.

**Comment by shibumi** [comment]
well you said:
> However, i3blocks does not allow defining a background color it will transmit from the script (yet)

It's possible to set a background via pango. We should differ between a pango background and a full status block background. Thats what I wanted to say ;) Just wanted to make that clear.

**Comment by kb100** [comment]
@shibumi @Airblader You are both correct but are using different definitions of "background". @Airblader is referring to the block background property, whereas @shibumi is referring to the text background property.
The text background can be set using pango, the block background cannot. Hope this clears things up.
