### ISSUE TITLE
Status management for blocklets

### ISSUE THREAD

**Issue by rndusr** [vivien/i3blocks#108]
Some blocklets need to remember values from previous calls. CPU load and network usage, for instance, need their values from previous calls to calculate the difference.

From what I've seen, blocklet scripts use temporary files to save their status, but it would be nicer if i3blocks could manage that somehow for reasons of consistency, ease of use, increased performance and less file system clutter.

Could this be achieved with environment variables? Or something else?

**Comment by vivien** [comment]
This is an interesting idea. However, it may break the behavior of some existing scripts; need to think more about this.
In the meantime, if your script needs to remember some states, you may be interested into the `persist` special interval. See [this blocklet](https://github.com/vivien/i3blocks/wiki/Blocklets#focused-window) as an example. Its limitation is that it must output single lines; and clicks won't be interpreted as the script is already spawned.

**Comment by rndusr** [comment]
Ah, I didn't know about `persist`. I think this makes this issue completely
irrelevant.

If I understand it correctly, `persist` scripts run in an endless loop and
print updates whenever they want? IMO, this is the best method to get
information from scripts anyway because it doesn't constantly spawn new
processes, it displays updates as soon as they happen, and it also solves this
issue in a much better way than any IPC solution ever could.

The only problem I have is that it makes dynamic colors impossible. Is there
any chance `persist`ent scripts could print the same three lines?

**Comment by vivien** [comment]
Hi,

The issue is not irrelevant, but actually, the idea is to spawn a script with a clean environment (it got reset with the default values from the config before being spawn); so changing this behavior may bring some inconsistency.

For `persist`, yes, this means that your script is running indefinitely, and i3blocks should only care about single lines. Take this example:

```` ini
[date-plain]
command=while :; do date +%s; sleep 1; done
interval=persist
````

As you mentioned, this makes impossible to use the plain text format (3 lines for full, short texts and color). To work around this, we introduced the json format, see this:

```` ini
[date-json]
command=date +'{"full_text":"%s","color":"#00FF00"}'
interval=2
format=json
````

N.B. for colors, note that i3bar now supports the Pango markup; i3blocks introduces a `markup=pango` property; so a single line (plain text) is enough to control coloring.

**Comment by rndusr** [comment]
Great! `format=json` would solve my final issue.

I don't see a reason to use anything but `persist` for all scripts. The only
drawback is that each script has to implement its own endless loop, but those
are trivial in all languages. And it has all the benefits I mentioned in my
previous post.

Do you plan a new release with these features soon?

BTW: i3blocks doesn't complain when `interval` is set to nonsense. Earlier
today, I was scratching my head for a while wondering why `interval=persist`
doesn't work as expected before noticing that it's not in the 1.3 release I
use. Maybe some validation would be nice?

**Comment by Zopieux** [comment]
> I don't see a reason to use anything but `persist` for all scripts.

That's why I pushed this idea so hard a few months ago! Yet an actual interval does make sense when you you just want to query some data every few seconds.

About your validation stuff, [the code](https://github.com/vivien/i3blocks/blob/master/src/block.c#L362) uses `atoi`, so it fallbacks to zero if you give it nonsense. Feel free to open a PR that uses `strtol` and check for errors.

**Comment by rndusr** [comment]
> > I don't see a reason to use anything but `persist` for all scripts.
> 
> That's why I pushed this idea so hard a few months ago!

Thank you! :)

> Yet an actual interval does make sense when you you just want to query some data every few seconds.

I agree, but that should be a special case, IMO. But now it's too late; not
breaking compatibility is more important than sensible defaults.

> Feel free to open a PR that uses `strtol` and check for errors.

I'd love to contribute, but I don't know anything about C. Never heard of
`atoi` or `strtol`.

**Comment by vivien** [comment]
In addition to the *persist* interval, you can now inject and update any variable, see the example below:
```` ini
[foo]
command=printf '{"full_text":"%s","foo":%d}\n' $foo $((foo+1))
format=json
interval=1
foo=1
````
This blocklet will increment and print the variable *foo* every second.
