### ISSUE TITLE
status_command exits unexpectedly when config is symlinked

### ISSUE THREAD

**Issue by 97-109-107** [vivien/i3blocks#120]
Steps:
- have a working config
- move it elsewhere
- link it back into place via ``ln -s /full/path/to/new/place /home/user/.config/i3blocks/config``
- reload i3wm
- see "Error: status_command process exited unexpectedly (exit 1)"
- open the config file
- make any change (remove line, add space, etc)
- reload i3wm
- works

**Comment by Nycroth** [comment]
I tried to replicate it.

I have my config in `~/.config/i3/i3blocks.conf` and call `status_command i3blocks -c ~/.config/i3/i3blocks.conf`. I moved it to a `.bak` file and symlinked it back. Worked without incident.

Dropped the `-c ...` and symlinked the new file (`~/.config/i3/i3blocks.conf.bak`) to `~/.config/i3blocks/config`. Worked without incident.

Are you sure it's a symlink issue and not a config issue?
>* make any change (remove line, add space, etc)
>* works

Seems it was just a config problem. Otherwise I'll need more details to debug.

**Comment by 97-109-107** [comment]
Indeed it was a case of ``... is not terminated by a newline`` - in my report I omitted a step where the config file was being generated by a template engine ([themer](https://github.com/S0lll0s/themer)). 

Thanks to your answer I figured out i can debug this directly in bash using ``i3blocks -c config.file``
