### ISSUE TITLE
Suffix label

### ISSUE THREAD

**Issue by alexbooker** [vivien/i3blocks#142]
Hi,

I'm just wondering if it's possible to create a *suffix* label e.g.:

```
[disk]
command=/home/booker/.i3/scripts/disk
interval=1
label=
suffixLabel="space left"
```

```
 200GB space left
```

Many thanks.

**Comment by kb100** [comment]
Regardless of whether this is added to i3blocks, you can accomplish this with either of the following modifications:

    [disk]
    command=/home/booker/.i3/scripts/disk | awk 'if(NR==1)print($0" space left");else print}'
    interval=1
    label=

    [disk]
    command=/home/booker/.i3/scripts/disk | sed '1s/$/ space left'
    interval=1
    label=

**Comment by alexbooker** [comment]
It never occurred to me that I could do that.

Thanks @kb100!

**Comment by vivien** [comment]
Hi @alexbooker! I prefer not to add new options for the moment, I'll provide a more flexible way to pass arguments to blocklets. I'm closing this issue, thanks!

**Comment by sammko** [comment]
The solution provided by @kb100 does not seem to work in the case of `interval=persist` blocklets like this one https://github.com/Zopieux/i3blocks-contrib/tree/master/pulse-volume . This is weird, becuase manually inputting the command into a shell yields exactly the same behaviour as the `pulse-volume` program by itself. Running `i3blocks` prints the following lines to stderr:
```
ERROR read_nonblock:70: read from 14: Bad file descriptor
ERROR block_update:203: [pulse-volume] pipe closed
```
Sometimes, the first line is not printed. Using a `sh -c "<the command>" type of thing, or putting the command into a separate shell script does not change anything.

Thanks for any ideas!

**Comment by kb100** [comment]
@sammko For persistent blocks you may also need to worry about stdout buffering, see https://github.com/vivien/i3blocks/issues/190

Also, I have already written a volume block for pulseaudio in i3blocks-contrib, https://github.com/vivien/i3blocks-contrib/tree/master/volume-pulseaudio, you may want to take a look at.

**Comment by sammko** [comment]
@kb100 ok, I'll try to figure something out. Yes, I have seen your script, but the nice thing about the one I linked is that I do not have to deal with any signals or polling -- it just works. I don't just want to add a `kill` into my keybinding because the volume can be changed from other places (for example pavucontrol). Multiple solutions come to my mind (in order of preference):

- Modify the `pulse-volume` program to output what I want it to
- Try to figure out what's actually wrong
- Modify the `pulse-volume` program to send a signal to i3blocks and use the `volume-pulseaudio` blocklet
- Live without a percent sign :smile:

**Comment by kb100** [comment]
@sammko Out of those options I think forking your own version of pulse-volume and adding a percent sign is the best choice. Bonus points if you make it a command line option and submit a pull request.

**Comment by sammko** [comment]
@kb100 Done and done. https://github.com/Zopieux/i3blocks-contrib/pull/1
