### ISSUE TITLE
Button disappears on click

### ISSUE THREAD

**Issue by Airblader** [vivien/i3blocks#144]
From the wiki:

````
[clickme]
full_text=Click me!
command=notify-send "Click at ($BLOCK_X,$BLOCK_Y) with $BLOCK_BUTTON"
```

As soon as the button is clicked, it disappears. Is this intentional? How can I make it stay?

**Comment by 8carlosf** [comment]
doesn't the command return value replace the full_text? and because the notify-send doesn't output any value, it refreshes to "". if you add a ` && echo "click me!"` at the end of the command..
(that's what I think it does, from testing it before)

**Comment by Airblader** [comment]
Then why would I use `full_text` at all in this situation? I could save the duplication and do this (which I did like a few minutes ago anyway):

````
command=echo "Click me"; [[ -z "${BLOCK_BUTTON}" ]] || /path/to/script
interval=once
```

Well either way, it's working, I guess. Thanks for the help!

**Comment by 8carlosf** [comment]
I don't know, but yes, unless you want a static message (I don't know why you would), that's a better smaller and better looking solution..
I had some other problems with the click 'thing', for example, I didn't manage to do something like, clicking in the cpu percentage and open a htop in a terminal, this locked the bar (the refresh stoped until I closed the terminal). even including a & in the end to fork the process.. and some other problems, I just ended up not using that kinda stuff, maybe it was me or my implementation of things, It wasn't really a problem, because I don't use the mouse that much anyway, so, the bar is mostly to show info.

**Comment by Airblader** [comment]
I do have a static message, because it's just a clickable icon. :) Forking via `&` seems to work for me.

**Comment by 8carlosf** [comment]
hm, maybe I was because I had a timer, and the command should still update even if I called htop before.. or I just don't remember it correctly.. anyway, happy to help :)
