### ISSUE TITLE
100% CPU load using repeat interval

### ISSUE THREAD

**Issue by donniebishop** [vivien/i3blocks#160]
Set my mpc block to use `interval=repeat` to immediately update the currently playing song in the bar, but whenever I set that, htop starts to climb and reports 100% CPU load. After removing the repeat interval and setting it to something even as frequent as `interval=1` brings the CPU all the way back down to ~15% load when idle. 

    [mpc]
    command=mpc current
    color=#d99db1
    interval=1
    #interval=repeat    # disabled due to 100% CPU load
    #signal=10

I'm currently using mpc, mopidy, and ncmpcpp, if that helps as well.

**Comment by kb100** [comment]
"repeat" means execute repeatedly as fast as possible. If you run an ordinary command with this mode it will indeed just burn cpu time. It only makes sense to set a block interval to repeat if the block command waits until something happens. Here are a few options for you:

1) Use signals, this is what they are meant for. Some media players have event based hooks that say "call this function whenever [X]" happens. Has a song change hook, have it call "pkill -RTMIN+10 i3blocks" and put  `signal=10` and `interval=once` in the config.

2) Use a watching daemon that watches for state changes in mpc. E.g. if you can find a file that mpc modifies whenever it changes song, you can use inotifywait (found in inotify-tools package) to wait for a state change. Then you could put you command as `mpc current && inotifywait [-flags]` so that the script doesn't immediately terminate and get called again.

3) Just sleep. Use `command=mpc current && sleep .5` in order to have the script called every half second. This introduces the necessary idle time so that you don't burn cpu, but offers higher polling granularity than the minimum `interval=1`. Don't set the amount of sleep time too low or you will end up cpu burning like before.

**Comment by donniebishop** [comment]
I was worried repeat was doing something like that. Makes total sense now.

Thank you for your suggestions! Though for the sake of ease, I'll probably just keep the interval on 1 because knowing what song is playing is really at most only a second away from an update. Just wanted to make sure this wasn't a larger issue.

Thanks!
