### ISSUE TITLE
No Battery indicator on iBook running Debian 8.2 ppc

### ISSUE THREAD

**Issue by Elowan** [vivien/i3blocks#161]
Hi there, I just can not get the battery 'ticker' going. I adjusted the path to the folder (uevent) location but nothing shows up. Before posting my configs and such, I may ask, if this is a common issue with that laptop and distro combination?

Best regards

**Comment by kb100** [comment]
All the battery script does is call and parse the output of acpi. If the battery script isn't working, it's probably because either you don't have acpi installed or acpi doesn't know how to get info on your battery. Indeed, getting a universal battery script is a difficult problem because that would rely on hardware manufacturers conforming to some open standard. Since that is a stretch (today) battery script problems are common.

If you go through the motions we can help you troubleshoot. Describe behavior when you run script on your bar, describe behavior when you run script from command line, what does acpi output, etc. 
 
You may also want to check out https://github.com/vivien/i3blocks-contrib which has an alternate batterybar script written independently of the one in this repo.

**Comment by jpleau** [comment]
There is no 'acpi' package on PPC for debian afaik: https://packages.debian.org/sid/acpi

I made sure that i3blocks doesn't depend on "acpi" package on architectures where it's not supported

If you find any alternative let us know so we can integrate it on the  battery scripts for i3blockcs!

**Comment by Elowan** [comment]
Thanks for answering and yes, acpi is not supported on PPC Debian. I could not find any script or Workaround, so I use conky right now, which works. Sadly not for the volume control, which iblocks handles well.
