### ISSUE TITLE
labels for all blocks except one disappeared on 1.4

### ISSUE THREAD

**Issue by zetok** [vivien/i3blocks#162]
Due to i3blocks "fighting" with workspaces for free space:
![works](https://cloud.githubusercontent.com/assets/3148759/12331523/d5842110-bae1-11e5-850d-801813bd3aea.png)
↓ and without labels, when one more ~~label~~ workspace is added:
![doesn't](https://cloud.githubusercontent.com/assets/3148759/12331564/f4bf3790-bae1-11e5-8f3f-a7aded8b31cf.png)

The only label that didn't disappear is `i/o:` one, not sure why - perhaps it matters that its block has in config `interval=persist` ?

Reproducible: Always

**Comment by kb100** [comment]
See http://i3wm.org/docs/i3bar-protocol.html and search for short_text. Basically, blocks should give two versions of the text to display, a full_text and a short_text, where the short text is displayed if there is not enough room for the full text. Short texts usually differ from full texts by removing labels or other unnecessary text. Due to the nature of persistent blocks, they can only provide full text, and thus it makes sense that this is the only one that isn't getting shorter.

What you have reported is consistent with the design of i3bar/i3blocks, so feel free to close the issue if you no longer think this is a problem. If there is something beyond what I have mentioned, please elaborate.

**Comment by zetok** [comment]
I see. Thanks for the explanation - I've reported it, since it didn't seem like a consistent behaviour, but since it apparently is, I'm closing the issue :)
