### ISSUE TITLE
What are/how to set first and second parameters?

### ISSUE THREAD

**Issue by NikosAlexandris** [vivien/i3blocks#200]
In https://github.com/vivien/i3blocks/blob/master/scripts/volume#L20, the second parameter is mentioned.
In https://github.com/vivien/i3blocks/blob/master/scripts/volume#L38, the first parameter is mentioned.

What are these parameters? How are they set (I guess in `i3blocks.conf`)?

**Comment by vivien** [comment]
Hi @NikosAlexandris, this script expects these parameters on the command line.
In the default configuration, the command defaults to something like `command=/usr/lib/i3blocks/$BLOCK_NAME` where `$BLOCK_NAME` is `volume`.

You can explicit the command with with its parameters like this:

```` ini
[volume]
command=/usr/lib/i3blocks/volume 10% pulse
label=♪
instance=Master
interval=once
signal=10
````

In the first line you linked, `MIXER="${2:-$MIXER}"` means in Bash "assign the MIXER variable with the second parameter if it is present, otherwise default to the value of MIXER".

**Comment by NikosAlexandris** [comment]
Makes sense. Thank you. Maybe add this very example `command` line in to the FAQ so as to explain optional arguments?

**Comment by vivien** [comment]
I think I will soon get rid of the global `command=` in the default config. While it is a cool hack to reduce boilerplate, it can be confusing for new users.
