### ISSUE TITLE
bandwidth units incorrect

### ISSUE THREAD

**Issue by CD3** [vivien/i3blocks#216]
The bandwidth script includes the following lines

```
# shift by 10 bytes to get KiB/s. If the value is larger than
# 1024^2 = 1048576, then display MiB/s instead

# incoming
echo -n "DOWN "
rx_kib=$(( $rx_rate >> 10 ))
if [[ "$rx_rate" -gt 1048576 ]]; then
  printf '%sM' "`echo "scale=1; $rx_kib / 1024" | bc`"
else
  echo -n "${rx_kib}K"
fi
```

Which incorrect because `rx_rate` is already in bytes/s (the file `rx_bytes` contained the number of *bytes* received). `rx_kib` should be `$rx_rate / 1000`, and MB/s should be calculated as `$rx_kib/1000`.

The same is true for transmitted bytes.

**Comment by kb100** [comment]
@CD3 Are you complaining that he divides by 1024 instead of 1000? If not I don't see what the issue is. In case it slipped your mind `$rx_rate >> 10` means bit shift right by 10, i.e. divide by 2^10 = 1024. You say `rx_kib` should be `rx_rate / 1000` and currently it is the more correct `rx_rate / 1024`. If I misunderstand your issue please elaborate to help me understand.

**Comment by CD3** [comment]
You know what, your right. I was thinking that it was doing a conversion from bits to kilobytes, but I forgot about binary prefixes.
