### ISSUE TITLE
BLOCK_INSTANCE is not working properly

### ISSUE THREAD

**Issue by janemba** [vivien/i3blocks#238]
Hi,

I have a problem with my blocklet. After debugging, I discover the issue is the BLOCK_INSTANCE which is not sent or not sent properly to my script.
```
$ cat i3blocks.conf
[...]
[battery]
command=~/.config/i3/blocks/battery
markup=pango
interval=30

[battery]
label=
instance=/org/freedesktop/UPower/devices/mouse_hid_90o7fo61o11o21o04_battery
command=~/.config/i3/blocks/battery
markup=pango
interval=30
[...]
```

```
$ cat blocks/battery
device=${BLOCK_INSTANCE:-/org/freedesktop/UPower/devices/battery_sbs_0_000b}
[...]
```

When using default value, it work fine. But when I set `instance` in i3blocks.conf I noticed that BLOCK_INSTANCE is not correct because `device` is not set to a correct value.

Do you know how can I debug this ?

**Comment by kb100** [comment]
Are you using an outdated i3blocks? Run i3blocks -V. If you see anything less than 1.4-17 then this is a known bug that has been fixed.

**Comment by kb100** [comment]
To clarify, the bug was that the BLOCK_INSTANCE variable was taken to be a 32 byte string. This has been updated to allow BLOCK_INSTANCE to be 256 characters long. It looks like official debian and arch packages are both out of date on this one, so if you want this fixed you will have to build from source (which is very easy, git clone, make, sudo make install). If you don't want to build from source, then you could just modify the script you are using and hard-code the device variable.

**Comment by janemba** [comment]
Ok, I was using an outdated version but...the last version in "releases" is outdated.
Problem fixed.

**Comment by kb100** [comment]
@vivien Can we get a bugfix release? It's been quite a while since the last one!
