### ISSUE TITLE
Change state after click for defined amount of time?

### ISSUE THREAD

**Issue by Alkotronikk** [vivien/i3blocks#253]
Please implement a way how to define a state change length after click event that couldbe different from the interval setting. 

Some of my block update every few seconds, some once in a minute and all my blocks are set to display additional information after click. But right now I'm getting times ranging from split of a second to the full interval duration and I'd love to make it more consistent.

**Comment by kb100** [comment]
Hi, just trying to understand what exactly you mean. What is a "state change length"? From context it seems like when you have a block with an interval, you want the interval to reset after a click with an optionally different time interval immediately following the click? Is that correct? As in

normal
1 2 3 block 1 2 3 block 1 2 3 block 1 2 3

with click
1 2 3 block 1 2 click 1 2 3 4 5 6 block 1 2 3 block

This would require a bit of reworking how clicks and intervals interact. Currently they are completely independent, i.e. every block interval i3blocks will call the block, regardless of when the last click occurs, which is why you observe the block executing anywhere from immediately after a click up to the full block interval.

As far as I know, I *think* (but am not quite sure) that i3blocks will queue up the next block execution if the current one hasn't terminated yet. So if things work the way I think they do, you could artificially extend a block interval immediately following a click by simply putting a `sleep 10` at the end of your script.

Could you give us more info on what blocklet specifically this is an issue with?

**Comment by Alkotronikk** [comment]
Hello, sorry that I didn't make myself clear. I want accomplish something like this:

normal interval 3:
1 2 3 block 1 2 3 block 1 2 3

normal with click lenght 1
1 2 3 block 1 2 3 click 1 block 1 2 3 

normal with click length 5
1 2 3 block 1 2 3 click 1 2 3 4 5 block 1 2 3 

My desired behaviour would be like this:
1. Block with interval 60 changes it's state (echo output) for 5 sec after click.
2. Block with interval 1 changes it's state for 5 sec too after click
3. (**Ideally**) this n sec long clicked state is configured via i3blocks.conf for every block and can be redefined for each separate block

**Comment by kb100** [comment]
I can see how this would be useful, but I think it is unlikely to be implemented any time soon (unless you do it) because it would require rewriting critical portions of the scheduler. At present, the best I can offer you is two alternative ways to get similar behavior.

1. Instead of having the click update the blocklet, have it call notify-send or zenity to give you a popup box with the info you need. This way the popup and the blocklet don't have to fight for space on your bar and the timing issue shouldn't be as much of a problem.

2. Create a persistent notification blocklet. All it does is sit and wait for input from a fifo file in a loop. Whenever it receives input from the fifo, it displays it and sleeps for 5 seconds before going back to wait for more fifo input. If you really wanted different waiting times for different blocks, you could instead always write two things to the fifo, a time, and a message.

**Comment by Alkotronikk** [comment]
I downloaded the source hoping for easy implementation, but I'm not good enough with C++, so I guess I'll give a go to the option 2. with persistent blocks, since I don't really want too much notifications going on.

Thanks for your time.
