### ISSUE TITLE
position = left with text on right

### ISSUE THREAD

**Issue by janemba** [vivien/i3blocks#260]
Hi,

I would like to know if it is possible to position a blocklet on the left ? I tried to make it using the following key :
```
min_width=
```

So it works fine but is it possible to do it dynamically ?

**Comment by vivien** [comment]
In addition to `min_width`, i3bar has an `align` key you can play with. Using the JSON output, you can update them from your script output if you need to, and/or add a default value in your blocklet's configuration.

**Comment by vivien** [comment]
Wouldn't it be simpler to have 2 blocks ? one print the text on left, the other printing the text on right. If you give me a proper example I can try to provide valid examples.

**Comment by janemba** [comment]
Well, unfortunately I tried to do that but without success. So here a valid example with min_width but the problem is the text length change (with a maximum of 80 columns).

```
$ cat i3blocks-top.conf
# i3blocks config file

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=~/.config/i3/blocks/$BLOCK_NAME

full_text=〉
#align=center
color=#FFFFFF
separator_block_width=15
markup=pango


# News
#
[news]
interval=10
align=left
min_width=3240

# Date
#
[date]
interval=5
color=#9C9D47

$ cat news
echo "test"
```

So the date is perfectly align on the right side and the block new also but **only** with static text.

**Comment by vivien** [comment]
i3bar does not currently support alignment of the whole status line output, only alignment of text *within* blocks. So this only option you have is to force *min_width* depending on your screen width, in a bar without workspace button or tray output (otherwise you'll have to deduce their width as well, which can be tricky.)

Here's an example for my *VGA-1* output which is 1920x1080.

In the i3 config:
````
bar {
  output VGA-1
  position top
  tray_output none
  workspace_buttons no
  status_command i3blocks -c /tmp/janemba.conf
}
````
And the i3blocks config:
```` ini
# Global properties
separator_block_width=0
separator=false

[left]
min_width=960
align=left

color=#FFFFFF
# For some reason i3 chomp a char on the very left, so output a single space first
command=echo -n " "; test $(($(date +%s) % 2)) -eq 0 && echo "This is a loooooong text!" || echo "Short text."
interval=1

[right]
min_width=960
align=right

color=#9C9D47
command=date
interval=10
````
Note that you can easily compute the *min_width* value from your script using *xrandr* and a global variable `$ouput` for instance, as well as using the json format for your block.

**Comment by janemba** [comment]
Thanks !! It works fine.

**Comment by vivien** [comment]
Note that the  first char won't be chopped anymore in the next version of i3bar (https://github.com/i3/i3/issues/3404).
