### ISSUE TITLE
A better way to determine block order.

### ISSUE THREAD

**Issue by MR4Y** [vivien/i3blocks#266]
The way you currently have for ordering blocks is cumbersome and requires too much text editing, as the blocks are shown in the order they are in the config script. If I only want to change which order they appear, I have to move several blocks of text around and hope it doesn't break the config file. I don't know why it's scripted that way, considering i3status with i3bar has an 'order' line before all the widgets where you can set in which order they appear.

**Comment by vivien** [comment]
IMHO following the ordering of the configuration file is intuitive. Having to write an extra `order` statement seems annoying and not very KISS. What is it you're suggesting?

I'm not against defining an i3blocks-specific configuration syntax if this would really add a value.

**Comment by MR4Y** [comment]
This would make easier to quickly order the elements of the bar without having to copy and paste blocks of text over the order they should be, especially if you have several custom blocks, for example.

**Comment by kb100** [comment]
@MR4Y I agree with @vivien on this one. An order directive is an unnecessary complication since changing the order of blocklets is something that will rarely be done after initial setup. If you REALLY want to change the order of your blocklets all the time, you may want to write a script that parses your config and then asks you what order you want to put the blocklets in, then outputs a new config with the blocklets in the new order.
