### ISSUE TITLE
Error when sending unicode characters via python script

### ISSUE THREAD

**Issue by udiboy1209** [vivien/i3blocks#268]
I have written a custom script for CMUS song display in python. When I output unicode characters like `\uf04b` or `\uf04c` through echo, they display correctly.

```
[cmus]
command=echo -e "\uf04b"
```

But If I try printing the same from python using `print(u'\uf04b')`, then i3blocks will not update the cmus block at all. Verbose output will show this

```
DEBUG setup_timer:84: starting timer with interval of 10 seconds
DEBUG json_print_bar:147: [cmus] no text to display, skipping
DEBUG block_spawn:293: [cmus] forked child 1569 at 1511406538
DEBUG sched_start:177: received signal 17 (Child exited)
DEBUG bar_poll_exited:121: [cmus] exited
DEBUG block_reap:313: [cmus] process 1569 exited with 0
DEBUG block_update:229: [cmus] updated successfully
DEBUG json_print_bar:147: [cmus] no text to display, skipping
```

What could be the problem?

**Comment by kb100** [comment]
It's hard to say what the error is without seeing the exact script you are running. Many of the python scripts I have written for https://github.com/vivien/i3blocks-contrib include printing unicode characters. https://github.com/vivien/i3blocks-contrib/blob/master/battery/battery is a good example.

My best guess is that you font you are using for your bar doesn't have the symbol in question, and you need to use pango formatting to change the font to one that does. For example, in my battery script when no battery is found, I write

    fulltext = "<span color='red'><span font='FontAwesome'>\uf00d \uf240</span></span>"
    ....
    print(fulltext)

Bash and other shells sometimes automatically change to a different font if you try to print a unicode character not supported in the current font, so that is why you wouldn't notice this from the command line.

Finally, instead of writing your own blocklet for cmus, you may want to use https://github.com/vivien/i3blocks-contrib/tree/master/mediaplayer which does support cmus. If it isn't satisfactory to you out of the box you may want to add new feature and contribute it back to us ;)

**Comment by udiboy1209** [comment]
I noticed you were using python3, while I was using python2 for my script. That may be the issue there. I am pretty sure font isn't the issue because I am using a nerd-font with other bash and perl scripts that I have, and other characters display fine.

I think I saw your cmus script from some post on reddit, but I wanted different icons for when the song was playing vs. paused so I went on to implement my own version. I finally wrote it in bash. Thanks for the help, anyway!

**Comment by yrizk** [comment]
i had the same problem, but something more elementary. I was just following the description for pango here: https://github.com/vivien/i3blocks/wiki/FAQ

/etc/i3blocks.conf
```
[icons]
command=echo "smile: \u263a, plug: \uf1e6, battery: <span font_desc='EmojiSymbols'>\U0001f50b</span>"
markup=pango
interval=once
```
again, echo worked. 
```
➜  ~ echo 'smile \u263a'
smile ☺
```
but the same command just printed the unescaped unicode sequence. 
-no python version
-font used by terminal and i3config are identical.
**anyways, I fixed it** by adding -e. Thanks to @udiboy1209 , I got curious to what the -e was doing and decided to give it a try! 
think that FAQ may need an update.
