### ISSUE TITLE
WiFi problem

### ISSUE THREAD

**Issue by hamzamuric** [vivien/i3blocks#283]
I get no output with wifi script in terminal and in i3blocks I only get % sign without percentage value

**Comment by kb100** [comment]
Hi, scripts are being migrated out of i3blocks and into i3blocks-contrib, so in the future please make issues with blocklets at https://github.com/vivien/i3blocks-contrib. In the meantime, in order for us to diagnose your problem, we need some more info. Would you please post the section of your i3blocks config related to the wifi block, and would you please also post the output of the wifi script when run from the command line.

**Comment by hamzamuric** [comment]
`# [wifi]
# instance=wlp6s0
# label=
# interval=10
# separator=true`

There's no output with wifi script

**Comment by kb100** [comment]
It appears the first line defining the blocklet is commented out

    # [wifi]

Using the `#` symbol like that at the beginning of a line starts a comment and i3blocks ignores comment lines.
Delete the `#` symbol in your config and let me know if the problem persists.

**Comment by hamzamuric** [comment]
I commented it because it does'nt work

**Comment by kb100** [comment]
I see, in order to post code in github, you have to prepend four spaces to the beginning of each line, that's why your previous comment got all messed up.

As for the actual issue... the reason you are getting no output from the block at the command line is because the block needs to know the interface. Try running the block from the command line like this

    BLOCK_INSTANCE=wlp6s0 /path/to/script/wifi
