### ISSUE TITLE
Error: status_command process exited unexpectedly (exit 1)

### ISSUE THREAD

**Issue by Surajpal2908** [vivien/i3blocks#300]
Hi developers, I'm getting some problem after installing i3gaps and i3blocks. The problem is that on the bar there is an error displaying saying "Error: status_command process exited unexpectedly (exit 1)" I tried reinstalling i3blocks (both from source and package from AUR) but I can't make it work. So a help will be appreciated. my i3 config file is here https://pastebin.com/0VraM616

**Comment by okraits** [comment]
What happens if you run the command set as `status_command` from a terminal?

**Comment by Surajpal2908** [comment]
it says "zsh: command not found: status_command"

**Comment by kb100** [comment]
@Surajpal2908, the error you indicated is from i3blocks, not from i3, so you need to post your i3blocks config file for us to help you.

**Comment by anosnowhong** [comment]
@kb100  same issue here, my i3block version is "i3blocks 1.4-32-g403308b". Seems that "border_top" "border_right" "border_left", these keywords are not recognized by this version of i3blocks. I just copy a i3block config from the internet, the functionality of these **border_** keywords is just a toggle to show or hide part of the block border. If this is not been set, a default rectangle box is shown.

**Comment by vivien** [comment]
Hi guys,

This error is because the currently releases of i3blocks only support known keys, as described by the i3bar protocol. However i3gaps uses additional keys, such as `border_top`. This key is unknown to i3blocks, thus the failure. But this is work around in the current master branch, which now has support for dynamic properties, which means any `key=value` pair are supported in both the configuration file or the blocklets output. All keys are passed to i3bar, which means the latest master of i3blocks should just works with i3gaps additional properties.

**Comment by bugb** [comment]
Still got the issue with the latest i3blocks version + i3gaps, is there any idea @vivien ?

Updated: my bad, make it works now!
