### ISSUE TITLE
scripts/bandwidth and scripts/iface fail on Slackware Linux 14.2

### ISSUE THREAD

**Issue by somospocos** [vivien/i3blocks#305]
Tested with i3blocks-1.4 and a simple ~/.config/i3blocks/config:

    [bandwidth]
    command=/path/to/scripts/bandwidth eth0
    interval=1

Symptomps:

1. i3 doesn't display any status bar at all

2. i3blocks doesn't contain any input from the script when being run manually

3. only manually running scripts/bandwidth produces the following output:

    $ ./bandwidth
    ./bandwidth: line 23: ip: command not found
    down
    down
    #FF0000

This is expected since in Slackware **ip** is actually **/usr/sbin/ip**, which is not in **PATH** environment variable by default for regular users.

Easiest mitigation is probably to add a comment at the top of bandwidth script, stating that the script uses **ip** from iproute2 and that it must be in **PATH**

Edit: scripts/iface is affected by the same problem

**Comment by vivien** [comment]
Hi @somospocos,

Thanks for the report. I've also experienced errors with the bandwidth script. Ideally this script should be converted as a `persist` loop, so that it is easier to maintain cache variables instead of a cache file.

However the default scripts bundled with i3blocks have been moved to [i3blocks-contrib](https://github.com/vivien/i3blocks-contrib/). The best would be to propose in improvement there.

Thanks!
