### ISSUE TITLE
Label no longer showing

### ISSUE THREAD

**Issue by Jab2870** [vivien/i3blocks#318]
With the latest release, the label set in the config is no longer output to the bar. I imagine this probably has something to do with all the options set in the config being passed to the script.

If the script is supposed to echo the label now, I suggest adding this point to the readme as it is quite a significant change.

**Comment by vivien** [comment]
Hi Jonathan, you are totally correct. While trying to be convenient, this was counter intuitive for things like the *min_width* calculation. With support for arbitrary options, this can easily be handled by the script. I wanted to deprecate *label* but this can still be a valid variable for the user, and removing it completely will "just" shorten the bar output, so I choose this option. I haven't update the documentation yet because I will rewrite it from scratch once I've finished reworking things up. Thank you!
