### ISSUE TITLE
Can block colors be loaded dinamically?

### ISSUE THREAD

**Issue by ltgouvea** [vivien/i3blocks#322]
For example, I have the following palette defined in an `colors.sh` file (generated by https://github.com/dylanaraps/pywal) 
```
# Colors
color0='#070c22'
color1='#6b72cd'
color2='#5992c8'
color3='#cb65a5'
color4='#a472d0'
color5='#cb8463'
color6='#dd9ab8'
color7='#a8b2de'
color8='#5165be'
color9='#6b72cd'
color10='#5992c8'
color11='#cb65a5'
color12='#a472d0'
color13='#cb8463'
color14='#dd9ab8'
color15='#a8b2de'
```
I would like to know if it's possible to access those variables in my i3blocks config file so that the palette would change automatically. Thx!

**Comment by vivien** [comment]
You have mostly 3 ways to do that.

1) Source this file in your scripts, so that you can access `$color3` from them. This requires to be shell scripts obviously.

2) Make this script executable and add code so that you can return the value from a call like `./colors.sh 3 #=> return #cb65a5`.

3) Use the latest master of i3blocks (not release yet) which supports any key-value pairs, and simply put the content of this file into at the top of your config file. That way all your commands will be executed with a `color3` environment variable and so on. Remove the quotes for this option!

**Comment by Kevin-Mok** [comment]
I've read a few issues on the topic (https://github.com/vivien/i3blocks/issues/279, https://github.com/vivien/i3blocks/issues/328), but I still can't figure out how to really do this. So, I have my `.zshrc` sourcing `colors.sh` such that `foreground` is an environment variable, and I want to use this to set the global color option. How can I do this?

**Comment by Kevin-Mok** [comment]
Hmm. This does work, but I was wondering if there was a way I could set the global default color using the variable instead of sourcing the colors in every script and formatting them individually.
