### ISSUE TITLE
Supporting new click modifiers discussion

### ISSUE THREAD

**Issue by kb100** [vivien/i3blocks#345]
This is just to get discussion started about whether/how we should support the new click modifiers that i3 sends. Currently they are just ignored, but I think that in the long run it would provide some increased flexibility for block creators to have these click data available. As I see it, there are 3 interfaces we could provide to the user:

1. Provide a CLICK_MODIFIERS int, which standard masking can be used to recover the variables. This is how click modifiers are stored internally in X. https://xcb.freedesktop.org/tutorial/events/. Advantages are that we only add one new variable and have minimal extra memory footprint.
2. For each modifier, provide a variable such as CLICK_MODIFIER_SHIFT that is set if the corresponding value is found in the array passed to us by i3. Advantage is ease of use for block writers not familiar with C-style bitmasking.
3. Pass the array as is that is handed to us from i3 and hope the user will parse it correctly. Advantage is minimal extra work on our end.
4. Keep as as is, don't support modifiers.

What do you think?
Related: https://github.com/vivien/i3blocks/issues/335

Edit: See xproto.h (/usr/include/xcb/xproto.h on my system) for how X stores modifiers. On my system the definition is

```C
typedef enum xcb_mod_mask_t {
    XCB_MOD_MASK_SHIFT = 1,
    XCB_MOD_MASK_LOCK = 2,
    XCB_MOD_MASK_CONTROL = 4,
    XCB_MOD_MASK_1 = 8,
    XCB_MOD_MASK_2 = 16,
    XCB_MOD_MASK_3 = 32,
    XCB_MOD_MASK_4 = 64,
    XCB_MOD_MASK_5 = 128,
    XCB_MOD_MASK_ANY = 32768
} xcb_mod_mask_t;
```
   
and the place where i3bar uses these can be found at https://github.com/i3/i3/blob/next/i3bar/src/child.c. Currently, the modifiers i3bar passes to us are:
```C
    ystr("modifiers");
    yajl_gen_array_open(gen);
    if (mods & XCB_MOD_MASK_SHIFT)
        ystr("Shift");
    if (mods & XCB_MOD_MASK_CONTROL)
        ystr("Control");
    if (mods & XCB_MOD_MASK_1)
        ystr("Mod1");
    if (mods & XCB_MOD_MASK_2)
        ystr("Mod2");
    if (mods & XCB_MOD_MASK_3)
        ystr("Mod3");
    if (mods & XCB_MOD_MASK_4)
        ystr("Mod4");
    if (mods & XCB_MOD_MASK_5)
        ystr("Mod5");
    yajl_gen_array_close(gen);
```

**Comment by xPMo** [comment]
As long as the array is passed when a blocklet requests json format, then I'm content with option 4.  Otherwise, option 1 is fine, it's not like bash one-liners will be parsing click modifiers... right?

**Comment by xPMo** [comment]
[Proof of concept](https://i.imgur.com/8Xr40A8.png)

```bash
#!/usr/bin/env bash
CLICK_MODIFIERS="${CLICK_MODIFIERS:-0}"

# shift lock control alt mod2 mod3 super mod5
mods=('S' 'L' 'C' 'A' '?' '?' '$' '?')

echo -n $'\e[90m'
for i in 0 1 2 3 6; do
	if (( CLICK_MODIFIERS & (1 << i) )); then
		echo -n $'[\e[0m'"${mods[$i]}"$'\e[90m]'
	else
		echo -n "[${mods[$i]}]"
	fi
done
echo $'\e[0m'
```

**Comment by gportay** [comment]
@kb100, @pstray, @xPMo: the commit is now ready if you wanna test.

**Comment by vivien** [comment]
Thanks @kb100 for digging into this.

I think that the modifiers must be injected into the environment with a choosen convention as suggestion by @gportay, like `modifiers="Shift Mod4"` or `modifiers=Shift:Mod4` (as commonly used with `$*PATH`) since environment variables are just key-value string pairs.

However persistent blocklets using the json format must receive the modifiers on their stdin as a JSON array (as passed by i3bar) like @xPMo mentioned.

I'll work on those `struct map` to make this easier.

**Comment by vivien** [comment]
The branch "modifiers" adds supports for flat nested arrays. This also implements @kb100's option 3. The modifiers array must be passed as is to the environment and must be a valid JSON array received on stdin for persistent blocklets using the JSON format. Let me know how this fit for you guys.

**Comment by vivien** [comment]
I've merged a better JSON parsing version into master. The nested JSON structures (arrays and objects) are stored and dumped as is, which means JSON aware persistent blocks must receive the modifiers as a JSON array.

The `modifiers` environment variable will be equal to `["Control","Shift"]`. Thinking about it I do not think it'd be necessary to push a custom array format as `echo "$modifiers" | grep -wq Shift` will work just fine with a JSON array or space/colon separated list.

I'm closing this since the current master since usable, please reopen if that isn't convenient enough for your scripts.
