### ISSUE TITLE
Background processes must still finish before i3blocks becomes responsive again?

### ISSUE THREAD

**Issue by Flurrywinde** [vivien/i3blocks#354]
I have a blocklet for adjusting the volume that's been working fine. Then today, I tried to add a call to `dzen2` to that blocket's bash script to make a box appear for 1 second, showing a volume bar. The call to `dzen2` is put in the background with `&`.

If I call the blocket's script from the command line, it works fine. I can run it many times quickly in a row.

However, when i3blocks calls the script, it seems i3blocks waits for even the background `dzen2` process to finish before it will process another click. This means that when I click on the blocket to adjust the volume, I have to wait 1 second for the dzen popup box to disappear before i3blocks becomes responsive again.

Is there a way to make i3blocks responsive to new clicks right away? I'm putting the `dzen2` call in the background, so why does i3blocks still wait until it finishes before becoming responsive again?

**Comment by kb100** [comment]
i3blocks does not wait for all background processes. Rather, the shell you are calling your program from is doing the waiting. This is the default behavior e.g. in bash (try opening a terminal, calling `sleep 10&` and then calling `exit`, it will fail). You must disown the child processes in order to get your desired behavior. Call the background process with `i3-msg exec -q yourscript` to achieve this.

**Comment by Flurrywinde** [comment]
This worked. Thanks!

**Comment by kb100** [comment]
@Flurrywinde Great! Please close this issue now that it is solved. (I can't since I am not a maintainer of i3blocks, only of i3blocks-contrib)

**Comment by Flurrywinde** [comment]
Done. Thanks again.
