### ISSUE TITLE
Question: Weird values when clicking on the blocklets

### ISSUE THREAD

**Issue by leon9923** [vivien/i3blocks#355]
Hi,

I am quite new to i3blocks, so I copied few of the blocklets from the i3blocks-contrib and also using the prebuilt ones.
So I noticed a weird bug in few of the scripts. On clicking the script  blocklet, the values go haywire. I don't have any experience in perl, but I tried to read the code I couldn't find the $BLOCK_BUTTON being used.

for example

> ~/.config/i3blocks/config
```
[battery]
#label=BAT
label=⚡
#instance=1
interval=30
```
The script is the battery one from i3blocks-contrib
https://pastebin.com/raw/yBeSv90J

Is there any way to make the blocklet unclickable in perl or via i3blocks, any solution would be helpful.

Thanks!

**Comment by kb100** [comment]
Welcome to the i3blocks community! For future reference, issues related to blocks themselves should be submitted to i3blocks-contrib, not here, so I can take care of them. Issues here are more for issues with the scheduler itself.

In any case, I'm happy to try to help you here. Could you be more specific about what you mean by "values go haywire" (post a screenshot?) and also what led up to this. What version of i3blocks are you using? What version of font-awesome are you using? Specifically, what blocks are affected? Are any of them blocks that you wrote yourself? Many issues of this type are caused by a user writing a block that has side effects on other blocks. The battery block you posted does not use clicks at all, so clicking on it should do nothing more than run the block again.

**Comment by leon9923** [comment]
Hi,
So sorry about that, I thought this seemed like a i3block issue.
I am using the i3blocks-contrib battery script the link is in the main post.

1. i3blocks 1.4-42-gb3de5e9 © 2014 Vivien Didelot and contributors
2. otf-font-awesome 5 
3. I found this issue particularly in the battery script and wifi script
4. No, I haven't written them.

Can I block the click request? that's whats happening the script is running again. Is there a way to make the block read only?

Thanks

**Comment by kb100** [comment]
It is not possible to block a click. Since the wifi and battery blocks in question don't change their behavior at all based on the BLOCK_BUTTON variable, this does not seem to be an issue with the scripts themselves. Have you tried isolating the block by making a temporary i3blocks config that only has one block in it?

**Comment by leon9923** [comment]
I will try creating a isolated script and see if it still happens. Thanks.
