### ISSUE TITLE
Click a block: blocks to the left disappear temporarily

### ISSUE THREAD

**Issue by jolange** [vivien/i3blocks#360]
i3blocks version: current master (c42bb1b)

When I click a block that takes a moment to update (for example CPU usage), all blocks to the left disappear and only reappear when the clicked block is updated.

You can reproduce it with this block:
```
[testblock]
command=sleep 2 && echo "the clickable block"
interval=once
```
Click it. The blocks left of that disappear and reappear after 2 seconds.

I bisected this to 8d89804f, but did not yet have a look at what might be the problem there.

**Comment by kb100** [comment]
@jolange, given my understanding of bugs like this in the past, my guess is that while the behavior may be different than before, it is occurring in a case that is not supposed to be occurring. Did this block *work* before? Or did it *freeze* all blocks for 2 seconds and then display?

A common bug report in i3blocks is something like "my bar is frozen after clicking!" and then in the config you see that clicking spawns a gui program. Indeed, i3blocks processes blocks in order and did not update any blocks until all blocks terminated (at least this is how it used to work, I'm not familiar with any new changes though). The solution that we have been telling people is essentially "This is expected behavior, spawn long running processes using i3-msg exec -q, not by calling the program directly". The reason for this (my guess) is that having any other kind of behavior would require multithreading, which introduces overhead and complexity that we would like to avoid.

To fix your problem, you might consider asking yourself, is it really necessary to sleep in my blocklet? Is the sleep because you want some other block to finish first and this is a poor man's mutex? If that is the case, consider having the other block or process emit a signal and using inverval=signal on your test block. You are welcome to ask for help with the real block if it is something you are willing to share. Most likely there will be a way around having a long-running operation as part of your block.

**Comment by kb100** [comment]
@jolange I just tested your testblock and I do not have the same behavior, it works as expected for me. HOWEVER, upgrading to the master branch has caused this behavior for me on a different block, the usb blocklet for me. I think there is a deeper issue here.

**Comment by kb100** [comment]
The behavior in my usb block is even stranger. All the blocks to the left of it seem to disappear if and only if an injected variable is a valid json array.

**Comment by kb100** [comment]
I've found the issue. The mentioned commit makes it so that when dumping the bar to stdout, values that are already valid json are not escaped. This results in a valid json array object to be sent on stdout to i3bar.
i3bar determines the callback for a value based on its type [here](https://github.com/i3/i3/blob/02bb2693f9a4c676d0e0a9f99bc648a7a4f98058/i3bar/src/child.c#L521), which for an array is the [stdin_start_array callback](https://github.com/i3/i3/blob/02bb2693f9a4c676d0e0a9f99bc648a7a4f98058/i3bar/src/child.c#L158), which (you guessed it) clears the status line, before it continues on processing the next blocks. This brings up two issues:

1. We are dumping ALL block properties to stdout for i3bar to eat. This depends on the currently true but not necessarily true in the future premise that i3bar will ignore unknown keys. It is also probably slower since this is extra data that does not need to be passed. I presume the reason this is this way at all is to make debugging easier so that all the bar variables can be seen. I believe this behavior should be disabled unless we detect that we are writing to a terminal and not to i3bar's ipc route, AND a debug mode is enabled.

2.  Additionally, this can mess with someone outputting a string that happens to be valid json, such as "[]", the quotes will get eaten and only [] will be printed with echo '"[]"'.

**Comment by vivien** [comment]
Thanks for the report @jolange and @kb100 for the investigation! I allowed arbitrary keys to be passed to i3bar in order not to make a new release every time a new key is understood, as well as adding support for forks such as i3-gaps which understand additional keys, but this ends up being messy.

The proper solution is to add support for multiple output formats now, such as *i3bar*, *i3-gaps*, [*terminal*](#134), and eventually arbitrary keys with a new command line option. I kept that for a future release but it looks like it is required now! I'll get back to you soon.
