### ISSUE TITLE
Colored labels

### ISSUE THREAD

**Issue by merspieler** [vivien/i3blocks#364]
I've tried to color the label as described in the "How can I give my blocks colors?" section in the FAQ in the wiki.

```ini
[volume]
label=<span color='#00c0d6'></span>
markup=pango
...
```

This results in a vanished block.

I'm running version 1.4 on debian buster.

Is this my fault or is it not yet possible to color just the labels like that?

**Comment by kb100** [comment]
I just tried this on my setup and it does give a colored label. Unfortunately we haven't had a release in over a year, so v1.4 is a year out of date. We recommend using the git version at least until we get another release out, as this was likely a bug fixed long ago. It is very simple to compile and install the git version, so please consider this choice.

**Comment by merspieler** [comment]
I'll try that and report back

**Comment by merspieler** [comment]
Worx ... tho i would appreciate an option like `label-color` just to make the config more clean... if you do not consider adding that option feel free to close the issue

**Comment by kb100** [comment]
I can't close issues in this repo, only in the contrib repo, so you may want to do that yourself. It unlikely that a `label-color` field will be implemented on our end because i3bar does not have such a field, it only has `full_text` `short_text` `color` `background` `border` `markup` `align` `min_width` `name` and `instance`. Even `label` is our own concoction, which we are actually trying to get rid of (label support was removed and then added back due to user backlash since we didn't provide a suitable alternative or conversion script) in favor of scripts just outputting the label they user and providing customization that makes sense for the script through injected properties..

**Comment by merspieler** [comment]
Ok...

**Comment by ahloiscreamo** [comment]
@merspieler 
Hi there,
just wondering, did you got it working.
i have the same problem (vanished block) on i3blocks version 1.4-6 (latest manjaro)
thanks man

**Comment by ahloiscreamo** [comment]
Nevermind, i found the i3blocks-git version on arch repo,
I installed that & everything work as expected.Cheers 🍻

**Comment by merspieler** [comment]
@ahloiscreamo just in case you can still make use of it:
```
[volume]
label=<span color='#00c0d6'>VOL </span>
```
That's how I get my labels collored differently tho i've got to do that for every single lable.

**Comment by ahloiscreamo** [comment]
Thanks for the guide @merspieler
i've done according to your snipplet and it work as expected,
Thank you very much!
