### ISSUE TITLE
xtitle -s doesn't work

### ISSUE THREAD

**Issue by 3N4N** [vivien/i3blocks#366]
I have the following in my i3block.conf:
```
[window]
command=xtitle -s
interval=persist
```
but it shows nothing

My xtitle is latest from the github, built from source, it works in the terminal, but not in the bar.

**Comment by vivien** [comment]
Hi @3N4N, i3blocks is doing what's expected here. The problem comes from xtitle itself. For some reason, when there are characters like a `-` in the title, it seems like it flushes stdout, or at least messes with it. This causes the kernel to send an I/O signal to i3blocks, which updates the blocks as expected.

For instance you will not have any issue with a fresh Firefox tab which only has "Mozilla Firefox" as its title. But I know that's not convenient. To workaround this flushing issue, you can pipe the xtitle output to cat, like this:

```` ini
command=xtitle -s | cat
interval=persist
````

**Comment by unattributed** [comment]
I've had this problem too. Piping into cat partially fixed the problem, but it's still empty intermittently.

**Comment by Hi-Angel** [comment]
FWIW, works for me with `command=xtitle -s -f`. Idk what `-f` option is doing as there's no man page, the `xtitle --help` doesn't explain anything, and googling "xtitle docs" doesn't come up with anything. But it's something you might want to try.

**Comment by Oktoras** [comment]
I think this is not cleanly xtitle issue. Because if I run xtitle -s from xterm, and then move around to different windows, xtitle updates the output correctly every time. Only when I run xtitle via i3blocks, output is sometimes empty (even with cat).

**Comment by vivien** [comment]
Closing this since `persist` works as expected. Feel free to reopen if I'm wrong.

**Comment by lucas-mior** [comment]
xtitle runs fine in a terminal, but in i3blocks it will just freeze in some window title and not update it self any longer, requiring i3 to be restarted.
