### ISSUE TITLE
Handle click events while block process is active

### ISSUE THREAD

**Issue by f4814** [vivien/i3blocks#382]
Currently `block_click` uses `block_spawn` to spawn the block on a click event. I see multiple problems with this:

1.) Using `interval=repeat` in combination with click events becomes impossible, because you have to hit the button in the exact moment when the block process has stopped and no new one has been started yes. (This is currently my problem)

2.) The more time your block `command` takes to finish, the more likely you are to get ignored by i3blocks.

To me this (or at least No. 1) seems like a serious problem.

I think it would make sense to allow spawning a second process when clicked, so we can always react to click events. I know this could break some scripts (if two processes create output at the same time) so maybe we could add an option, which allows us to ignore the blocks output if the process was called because of an cllick event.

I will send an PR if this is a desired feature. Just wanted to ask before starting to work on it :)

**Comment by vivien** [comment]
The click is actually specific to the i3bar protocol. i3blocks expects one command per block. When a block's environment is updated -- e.g. on click -- i3blocks will spawn the command with this environment, or write in the command's standard input if it is persistent. The "repeat" feature is kind of in between to provide a simple way to respawn a blocking command as soon as it exits. But indeed the limitation with this mode is that clicks are ignored.

I am not comfortable with writing to the standard input of such commands, because they are usually not designed for that, and we would race with their exit anyway. Describing multiple commands to run on left click, right click, wheel up and down and so on is a no-go, that is the responsibility of the commands to interpret the click data.

Maybe you can provide me a real life example of this "serious problem" you are encountering? I would like to get a taste of it and see how that can be worked around. Thank you!

**Comment by f4814** [comment]
I use `mpd` as my music player. MPD allows me to run `mpc idle` which will block until the player changes it's state (new song, paused, changed volume, you name it). This allows me to have my music block updated INSTANTLY as soon as something happens. But it prevents me from clicking the block to pause.

My current solution is to use `interval=10` but this leads to a 10 second lag in my bar.

Maybe we could kill the running command and restart it with the new environment. At the very least I think this limitation should be mentioned in the docs. (I know that it makes sense that you cannot change the environment variables of a process, but I do not think explicitly mentioning it would hurt)

**Comment by vivien** [comment]
Killing and restarting a command that is supposed to exit is hacky and unlikely to solve all problems. As I explain above, it is racy (you could still lose events during the kill and respawn time) and inefficient (some scripts may have lots of stuffs to initialize for example, so that is not i3blocks' job to decide whether the command should be stopped or not). If you want immediate update AND clicks, you must handle it in your script with a loop, making it a persistent block.

I do not know the details of `mpd idle`, but you could redirect its output to the standard input of your script which will only have to read input line by line, and make the block persistent. Let me know if you need help with that.
