### ISSUE TITLE
Indicators stopped working

### ISSUE THREAD

**Issue by qazip** [vivien/i3blocks#397]
My volume/cpu/internet indicators dissapeared ever since I updated i3blocks. The reason for that the location of the files changed. For example, the volume one is no longer in "command=/usr/lib/i3blocks/volume". Where is it now?

**Comment by geekdima** [comment]
OS: Arch Linux
i3blocks: 1.5

This is what happened to me to. I am not sure if this is i3blocks or Arch related.

I have this on top of my config:
`command=/usr/lib/i3blocks/$BLOCK_NAME`

but this directory no longer exist. Is this a packaging issue?

**Comment by putchar** [comment]
@qazip @geekdima as you can se eon the official documentation 
https://vivien.github.io/i3blocks/#_getting_started

 `The project’s repository does not include default scripts anymore. `

you can update your configuration file and use i3blocks-contribs located here https://github.com/vivien/i3blocks-contrib

**Comment by JadowityHerbatnik** [comment]
> The project’s repository does not include default scripts anymore.

I think that's only part of the issue, because I don't even use any of the default scripts provided and still, some of my custom scripts stopped working. They work correctly when executed from the terminal, but for some reason there's no output in the statusbar. 

Anybody got the same problem?

**Comment by 0x4c47** [comment]
Same issue here. It seems to be related to the Pango markup. All my custom block scripts except for one use Pango markup. Only the one not using Pango markup is working correctly now after the update.
When executing i3blocks from the terminal it also shows only the one without Pango. All the scripts executed independently work fine and return the correct Pango syntax.

I'm using the Source Code Pro font with Font Awesome 5 for icons in the bar. But since it's also not working from the terminal, I guess fonts are not the issue here.

**Comment by JadowityHerbatnik** [comment]
Awesome! Indeed, all of the broken scripts were missing newlines at the end of the output. One more issue I have however is that whenever a script gives an empty output, the bar still shows the icon/label (well, I guess it treats the new line character itself as a fully-fledged output).

I'm trying to think of some elegant way of fixing this other than just adding an if statement to every script to remove the new line character if the output doesn't contain anything else besides it.

**Comment by hicklemon** [comment]
Try cloning the blocks into your homedir and updating the config:

`command=/home/mynamehere/.config/i3blocks/$BLOCK_NAME/$BLOCK_NAME`

**Comment by Error916** [comment]
after 1.5 update i'm unable to make this two file working, can someone help me find the problem?

`#!/usr/bin/env sh
# Give a battery name (e.g. BAT0) as an argument.

case $BLOCK_BUTTON in
    3) pgrep -x dunst >/dev/null && notify-send "🔋 Battery module" "🔋: discharging
🛑: not charging
♻: stagnant charge
🔌: charging
⚡: charged
❗: battery very low!
- Text color reflects charge left" ;;
esac

capacity=$(cat /sys/class/power_supply/"$1"/capacity) || exit
status=$(cat /sys/class/power_supply/"$1"/status)

if [ "$capacity" -ge 75 ]; then
	color="#00ff00"
elif [ "$capacity" -ge 50 ]; then
	color="#ffffff"
elif [ "$capacity" -ge 25 ]; then
	color="#ffff00"
else
	color="#ff0000"
	warn="❗"
fi

[ -z $warn ] && warn=" "

[ "$status" = "Charging" ] && color="#ffffff"

printf "<span color='%s'>%s%s%s</span>\n" "$color" "$(echo "$status" | sed -e "s/,//;s/Discharging/🔋/;s/Not Charging/🛑/;s/Charging/🔌/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
`

and 

`#!/usr/bin/env sh

# Status bar module for disk space
# $1 should be drive mountpoint
# $2 is optional icon, otherwise mountpoint will displayed

[ -z "$1" ] && exit

icon="$2"
[ -z "$2" ] && icon="$1"

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send "💽 Disk space" "$(df -h --output=target,used,size)" ;;
	3) pgrep -x dunst >/dev/null && notify-send "💽 Disk module" "\- Shows used hard drive space.
- Click to show all disk info." ;;
esac

printf "%s: %s\n" "$icon" "$(df -h "$1" | awk ' /[0-9]/ {print $3 "/" $2}')"
`
both are the update version from [](https://github.com/LukeSmithxyz/voidrice/tree/archi3/.local/bin/statusbar)

**Comment by vcahlik** [comment]
Is there any reason why the default scripts are not included anymore? Is there a chance that they will reappear?

**Comment by vivien** [comment]
Indeed as of i3blocks 1.5, the default scripts were moved to [i3blocks-contrib](https://github.com/vivien/i3blocks-contrib) because it was hard to maintain. Sorry for the inconvenience.

Currently the commands can be relative to their config file, so you can have a folder for blocks (e.g. i3blocks-contrib) and use the `-c` option to point to its root config file (or you can have your blocks in ~/.config/i3blocks/ and let the program use the default ~/.i3blocks/config file).

That was just enough until one wants to use blocks from different directory trees, e.g. picking a single block from the contrib repository. For this I've implemented an `include` directive in the next branch, which might help to package complete status bars or even a single block and allow to specify `include=/usr/lib/i3blocks/config` or `include=~/src/crazyblock/config` from a user or system-wide configuration file. I'm not sure yet this is a must have feature so I'll keep it in next for now.
