### ISSUE TITLE
$SCRIPT_DIR doesn't expand from "~" to $HOME if quoted

### ISSUE THREAD

**Issue by glubsy** [vivien/i3blocks#398]
When calling i3blocks with the SCRIPT_DIR environment variable set with a "~" to refer to $HOME, i3blocks doesn't parse it properly if it's set between double quotes.

I have to explicitly call it with the full expanded path like this:

`status_command SCRIPT_DIR="/home/user/.config/i3blocks" i3blocks`
or like this
`status_command SCRIPT_DIR="$HOME/.config/i3blocks" i3blocks`

This works as suggested by the [FAQ](https://github.com/vivien/i3blocks-contrib/wiki/FAQ#blocklets-refer-to-script_dir-what-does-that-mean-how-can-i-use-it):
`status_command SCRIPT_DIR=~/.config/i3blocks i3blocks`

But this **doesn't work**:
`status_command SCRIPT_DIR="~/.config/i3blocks" i3blocks`

It's a very minor issue, but if there are spaces in the path, it might be a problem.

**Comment by zsugabubus** [comment]
Tilde ("~") is expanded by your shell and it has nothing to do with `i3blocks` or anything other in general.

> status_command SCRIPT_DIR="~/.config/i3blocks" i3blocks 

It _does not_ get expanded because double quotes means "literal string", and it would be a little strange if a generic "~" character, that stands for your home directory, would get unconditionally expanded even if you just wanted to store something totally unrelated in a variable (e.g. `MY_SEPARATOR_LINE="~o~o~o~"`.)

You can even try it in your shell:
```
SCRIPT_DIR=~/.config/i3blocks
echo $SCRIPT_DIR
SCRIPT_DIR="~/.config/i3blocks"
echo $SCRIPT_DIR
```

Just in case if you want to know more about [tilde expansion](https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_01) and [double-quotes](https://pubs.opengroup.org/onlinepubs/009604599/utilities/xcu_chap02.html#tag_02_02_03).

**Comment by glubsy** [comment]
That makes total sense! Thank you very much for taking the time to write this reply. :)

**Comment by zsugabubus** [comment]
What you may thought about is:
```
SCRIPT_DIR=myscriptdir
echo '$SCRIPT_DIR' # prints $SCRIPT_DIR
echo "$SCRIPT_DIR" # prints myscriptdir

SCRIPT_DIR='$SCRIPT_DIR'
echo "$SCRIPT_DIR" # also prints $SCRIPT_DIR ;)
```
