### ISSUE TITLE
Makefile: error when installing bash-completion

### ISSUE THREAD

**Issue by jpleau** [vivien/i3blocks#402]
Hi !

Working on updating i3blocks on debian/ubuntu, I encounter an error during `make install` (I think):

```
dh_auto_install -- PREFIX="/usr" LIBEXECDIR="/usr/share"
	make -j4 install DESTDIR=/packages/i3blocks/i3blocks/debian/i3blocks AM_UPDATE_INFO_DIR=no PREFIX=/usr LIBEXECDIR=/usr/share
make[2]: Entering directory '/packages/i3blocks/i3blocks'
make[3]: Entering directory '/packages/i3blocks/i3blocks'
( cd '/packages/i3blocks/i3blocks/debian/i3blocks/usr/share/bash-completion/completions' && mv bash-completion i3blocks )
 /bin/mkdir -p '/packages/i3blocks/i3blocks/debian/i3blocks/usr/bin'
 /bin/mkdir -p '/packages/i3blocks/i3blocks/debian/i3blocks/etc'
 /bin/mkdir -p '/packages/i3blocks/i3blocks/debian/i3blocks/usr/share/bash-completion/completions'
mv: cannot stat 'bash-completion': No such file or directory
```

Looking at Makefile.am, it seems we change directory and try to move the `bash-completion`script that is located in the source tree, but it doesn't exist because we just changed directory.

**Comment by alium** [comment]
i have same problem, same error

**Comment by alium** [comment]
because we need update this package, i remove broken part in Makefile.am and added manual to our PKGBUILD file: 
  # install bash-competion - broken in version 1.5
  mkdir -p $pkgdir/usr/share/bash-completion/completions
  install -c -m 644 bash-completion $pkgdir/usr/share/bash-completion/completions/i3blocks

[bash.patch.txt](https://github.com/vivien/i3blocks/files/3748355/bash.patch.txt)

**Comment by vivien** [comment]
@gportay would you have time to look into this?

**Comment by gportay** [comment]
#457
