### ISSUE TITLE
unicode characters break block output

### ISSUE THREAD

**Issue by vvvm23** [vivien/i3blocks#416]
When printing unicode characters in a python script the output is fine in console, but in i3blocks some of the outputs will be reversed.

Example:
```python
print("TEST: \ue286 ABC \ufb8a +123")
```

will output
`TEST:  ABC ﮊ +123`

reversing the positions of 123 + and ﮊ.

Removing ﮊ fixes the issue, but any other emoji causes the same problem.

Interestingly, while writing this it also reversed in browser, but in terminal it displays correctly.

**Comment by zsugabubus** [comment]
I think it’s more an issue with Pango, that is used by `i3bar` to display the text, the characters produced by `i3blocks`. You can easily verify the behavior using `pango-view`:

```sh
pango-view <(python -c 'print("TEST: \ue286 ABC \ufb8a +123")')
```

I think the issue here is that Pango don’t know that it will display an emoji and not an Arabic character at that code point (it totally depends on the font you are using). Then it guesses right-to-left “Arabic” direction and reverses the rest of the text.

A possible fix can be to explicitly state that you want left-to-right direction by using the [left-to-right mark](https://en.wikipedia.org/wiki/Left-to-right_mark).
It should be displayed correctly (*):

```sh
pango-view <(python -c 'print("TEST: \ue286 ABC \ufb8a\u200e +123")')
```

*: ±The used font.

**Comment by vvvm23** [comment]
that fixed it, thanks!
