### ISSUE TITLE
Feature Request: a conf.d facility

### ISSUE THREAD

**Issue by kgilmer** [vivien/i3blocks#417]
Use case: I have a desktop environment for which i3blocks is used.  I would like to have packages be able to "install" blocks, and have them be removed if the package is removed.  I concrete example is notification systems.  Both Rofication and Dunst are possible notification backends.  If using Rofication, I would like to display the count of open notifications via a blocket, but if dunst is being used instead, I do not wish to show anything.

Solution I would like: a `/usr/share/i3blocks/conf.d/` in which I can add/remove the stanzas that currently exist in the monolithic config file.  Packages can add/remove these files, thereby changing what blocklets render at runtime.  So, if Rofication is installed, this file would exist: `/usr/share/i3blocks/conf.d/10_rofication`, and if the package is removed, so would the file.  Upon start i3blocks would read and combine all stanzas into a complete config file that would then be parsed as is done now.

Concerns: 
* how to define ordering
* how to allow users to override default ordering
* how to deal with conflicts.

Is there any case in which i3blocks would consider a PR w/ this feature?  Is there some other way this can be achieved that I may be missing?

TIA!

**Comment by zsugabubus** [comment]
`i3blocks` is about customization. Some want icons, some want text, some wouldn’t like to see anything next to numbers (your example). Some want color, some want paddings, some want click events, some want a totally different thing. I do not see how your solution could be useful–if not harmful.

Why not let just every package installing a generic script that prints just a number (like [rofication-statusi3blocks.py](https://github.com/DaveDavenport/Rofication/blob/master/rofication-statusi3blocks.py)) and then everybody can use that inside her `command=` or such (or even in a totally different bar).

>  Packages can add/remove these files, thereby changing what blocklets render at runtime.

I already have a config file and I do not want blocks randomly popping up. Not even talking about if you use multiple instances of `i3blocks` with different configs.

> /usr/share/i3blocks/conf.d/10_rofication

Why not 11? I want to see it on the right of my custom blocklet.

> Concerns: …

> Is there some other way this can be achieved that I may be missing?

Solution: Add block as usual (two lines) and specify an absolute path in `command=` and you instantly get full palette of customizations. EZ.  What’s your problem with this?

**Comment by kgilmer** [comment]
Hi @zsugabubus , thanks for your response.  I could be wrong but I think there is some confusion as to what this issue is for.  The root cause that spawns this issue is that in the Debian packaging system, it is not cool for two installed packages to manage the same file.  So it follows that a monolithic config file may only be "owned" by one installed package at a time.  Given this, I have many packages that may all want to add some status indicator to i3blocks.  These packages cannot mutate the monolithic config file due to the packaging system.  I think, as a user of a system you wish to entirely manage yourself, then your own config file written in whatever way you like is 100% sufficient for your needs.  However, if you wish to treat i3blocks as a general purpose UI facility that can be generically extended by other packages without your direct control, then something like modular config files are necessary (at least for the Debian packaging system given my understanding of it.)

Generally when this question comes up, the response is "write your own upstream framework that produces a monlithic file from a whatever you like" but I do not want to do that for various reasons.

In any case, this work is already done in [i3xrocks](https://github.com/regolith-linux/i3xrocks), working, and people seem generally pretty happy with it.  At this point this issue is more of a notice for i3bocks developers, if they are interested in including this logic, I would be happy to prepare a PR.  It's actually a very minor change, although my implementation w/ command line parsing is admittedly very crude and a cleaner solution would be warranted for i3blocks.

**Comment by zsugabubus** [comment]
What I do not get: How could be a package distributed personalized config file could meet everyone needs? It’s not a config dir, like say… sysctl.d or fontconfig dir.

If you want to use one of the distributed configs you have to use conf.d in your local config otherwise you will not be able to set order.

If you want to override one of the settings or hide a block, you end up a `[block]\ncommand=` or a bunch of `/dev/null` symlinks.

…etc… I cannot find a reasonable usecase for it, where putting two lines into your existing `i3blocks` config would not be way much easier. User-local `conf.d` may be a thing but you can work around it by: (1) having multiple config files, (2) maintaining just a single file, (3) use some script to generate config (basically a `cat conf.d/* >myconfig`), (4) using `command=`s that check some condition, so block disappears if not needed.

> Both Rofication and Dunst are possible notification backends.

Do you change them daily or stick to one and use that throughout your lifetime? If latter, maintaining your config cannot be that hard.

And you expect every notification system should include and maintain an `i3blocks` config? And every other package that can be displayed in your bar? What’s your issue with `i3blocks-contrib`? Copy-paste code and that’s it.

Feel free to correct me if I do not get something.

**Comment by kgilmer** [comment]
Closing, feature was added to forked version of i3blocks.
