### ISSUE TITLE
A trigger from netctl to i3blocks

### ISSUE THREAD

**Issue by bensh4** [vivien/i3blocks#418]
- I've a 'Network' script, which will show up a network icon when network is connected and disappears it after disconnection. When I set `Interval= repeat`  in that block,Icon shows up right after connection/disconnection. But, code is continuously running and wasting resources. So interval in seconds is not convenient anyways. My question is,can I trigger i3blocks from netctl when connected/disconnected. Can I add a hook in netctl to signal i3blocks. I hope a signal handler is already enabled in i3blocks. But, which signal should I use and where? 
_Thank you, all!_

**Comment by zsugabubus** [comment]
For the same reason I wrote a C “script” that prints IP address and current bandwidth usage. It has nothing to do with `netctl` though, because it communicates directly with the kernel, thereby it can immediately react to any changes.
If you are interested in my solution you can find it [here](https://github.com/zsugabubus/i3blocks-native/blob/master/src/iface.c).

**Comment by zsugabubus** [comment]
But if you are not interested in bandwidth usage, you can simply use `ip monitor` to watch for changes.

**Comment by bensh4** [comment]
Using Networkmanager now!
