### ISSUE TITLE
Conditionally hide block

### ISSUE THREAD

**Issue by orestisfl** [vivien/i3blocks#430]
I feel that I am missing something very basic that I swear I could do in the past but I just can't find anything relevant.

What I am trying to do is to conditionally hide a specific block, including its label.

MWE:

```
[xxx]
label=hide me
interval=1
command=true
```

An example usecase would be something like `if swap memory > 0 then display swap usage else hide the whole block`.

**Comment by zsugabubus** [comment]
I’m not sure if you ever could do such thing with labels…

Personally, for blocks I want to hide, I print/generate label from the script output–at the end "label" is nothing more than a prefix. And I think it’s the preferred way, because `label=` had been deprecated in 37f23805ff886639163fbef8aedba71c8071eff8.

**Comment by orestisfl** [comment]
Thanks, you are correct :)
