### ISSUE TITLE
[Feature Request] multiple colors per block

### ISSUE THREAD

**Issue by kb100** [vivien/i3blocks#59]
I wrote a script to check what usb devices are plugged in and display their locations, labels, partitions, mountpoints, etc. E.g. the output might be

[sdd1] "flashdrive" /mnt/flashdrive: 8G | [sde1] | [sde2] /mnt/flashdrive2: 4G | [sdf1] "other"

if I had 3 usb devices plugged (sdd, sde, sdf), having 1, 2, 1 partitions (sdd1, sde1,sde2, sdf1), of which sdd1 is labeled "flashdrive", sdf1 is labeled "other", and sdd1 and sde2 are mounted.

Currently I can only color each block a single color, so the whole string above gets one color.
I would like to be able to color each of the sub-blocks a different color in order to indicate which ones are plugged versus which ones are actually mounted.

Note that, unlike for disk entries where I might have three fixed blocks for /home, /data/ and /, I do not know how many usb devices are going to be plugged in ahead of time, so I can't just use fixed entried with different colors.

**Comment by Airblader** [comment]
Multiple colors will likely soon be possible with i3 by using pango markup. See the pending pull request https://github.com/i3/i3/pull/1471

**Comment by vivien** [comment]
Neat! Thanks for the pointer @Airblader.

**Comment by Airblader** [comment]
And it's now merged! :) I've already been using it anyway and it's really handy. It allows more than just colors, e.g., font weight and strikethrough and stuff.

**Comment by valeriangalliat** [comment]
Since the Pango markup PR, the special HTML characters like `&`, `<`, `>` need to be replaced with corresponding HTML entities, otherwise i3status will not display the block.

It's maybe out of topic for this issue, but how do you think i3blocks should deal with this? By consequence of i3/i3#1471, i3blocks is currently assuming all blocks output is valid Pango markup. Should I update my blocks to encode special HTML characters? Or maybe a configuration option like `pango=true|false` is welcome in i3blocks (I would be happy to develop it and make a PR if so)?

**Comment by Airblader** [comment]
I'd suggest just encoding your block text. It's the most straight forward way for i3blocks. I guess i3blocks could support a pango property, though. Let's see what Vivien has to say. :)

**Comment by kb100** [comment]
We want to encourage people to come up with inventive use of pango, so I suggest adding a line to the default config

    # Use pango markup language for colors and other styling,
    # set to false to avoid needing to escaping HTML characters
    pango=true

I would opt to say just force people to use pango and don't even give them the option, but this might be too extreme. A newbie might get confused and think i3blocks is broken. Maybe add a default block that is commented out showing how to use escaped characters.

**Comment by Nycroth** [comment]
I'm going to be honest, I haven't found a decent Pango tutorial so I'm avoiding it. Any good sources?

**Comment by Airblader** [comment]
I found this sufficient: https://developer.gnome.org/pango/stable/PangoMarkupFormat.html

**Comment by valeriangalliat** [comment]
BTW I have a working implementation of escaping [here](https://github.com/valeriangalliat/i3blocks/commit/df7c5edfe146f27955529f79f8f7b6569ad664b4), for (at least) my personal usage (not yet configurable since I don't need Pango at all for now).

**Comment by vivien** [comment]
I don't get how Pango works with i3bar. Shouldn't this block work?
```` ini
[test]
full_text=<span foreground="blue" size="x-large">Blue text</span> is <i>cool</i>!
````

**Comment by acrisci** [comment]
@vivien that works for me in my statusline generator

**Comment by acrisci** [comment]
Another cool thing you can do is use icon fonts, such as

    <span font="FontAwesome">\uf0ea></span>

**Comment by vivien** [comment]
As @acrisci explained me, the font specified in the i3 config has to be `pango:` prefixed.

Also, concerning i3blocks, it seems like a per-block `escape` property (defaulting to true) needs to be added in order not to break existing scripts (we add a longer discussion on [Gitter](https://gitter.im/vivien/i3blocks)).

**Comment by valeriangalliat** [comment]
> Also, concerning i3blocks, it seems like a per-block escape property (defaulting to true) needs to be added in order not to break existing scripts.

:+1: for this.

There's another problem though; the Pango markup was introduced in i3 4.9.1. Before 4.9.1, escaping blocks output would result in raw HTML entities displayed (like `Kool &amp; the Gang` in my MPD block). But since 4.9.1, **not** escaping blocks would result in block not being displayed.

Typically, on Debian Wheezy, I have i3 4.8, while I have 4.9.1 on Arch, and if I want proper output everywhere, I need to [escape](https://github.com/vivien/i3blocks/compare/master...valeriangalliat:escape-pango) **only** on the latter.

Is it really i3blocks' responsibility to escape output? The thing is i3bar 4.9.1 broke existing scripts that could output special HTML characters, regardless if we use i3blocks or not.

Maybe it's i3bar that needs to support a `pango` property (defaulting to false) in the JSON protocol?

**Comment by vivien** [comment]
@valeriangalliat you are right. Ideally, the `status_command` program doesn't have to care about block texts. It makes sense to have a new `is_markup` or (`pango`) key to the i3bar protocol, since i3bar is in the best position to know if a bar is using a pango font and if a block needs to be escaped.

Something like this pseudo code for i3bar: `if (bar->font_is_markup && !block->is_markup) { print_escaped(block->full_text); }`

@acrisci what do you think?

**Comment by vivien** [comment]
@kb100 about your initial issue, with Pango this is now easy to build a convenient string for each USB device, that might look like this:
![](http://i.imgur.com/rHUJb6x.png) 
I cheated a bit with this static config:
```` ini
[usb]
full_text=<span foreground="green">[sdd1]</span> "flashdrive" <i>/mnt/flashdrive</i>: 8G | <span foreground="grey">[sde1]</span> | <span foreground="green">[sde2]</span> <i>/mnt/flashdrive2</i>: 4G | <span foreground="green">[sdf1]</span> "other"
````

*Note: alongside a udev rule to trigger a signal to i3blocks when an USB device is plugged/removed, this script is a good candidate for i3blocks!*

About the dynamic blocks, this is unlikely to be implemented, since I would prefer the i3blocks config to be as closed to the i3bar protocol as it can be, meaning a single blocklet matches a single i3bar block.

**Comment by acrisci** [comment]
Well we can't fix the problem with different versions not supporting pango markup in any case. That is a good complication to consider in the fix though.

Adding the per-block member for markup and defaulting to no markup I think might be the best idea so far. I'll work on it and see if I can get something simple enough for a dot release.

**Comment by kb100** [comment]
Closed: pango blocklets can have multiple colors.
