### ISSUE TITLE
Memory isn't accurate, MPD isn't showing

### ISSUE THREAD

**Issue by Grimmoire** [vivien/i3blocks#78]
The memory number seems completely arbitrary and nothing like what it actually is. MPC doesn't show at all. It used to work with "ncmpcpp --now-playing" but ncmpcpp removed that flag.
https://gist.github.com/Grimmoire/86fce9b2b22e803996aa
![i3bar screenshot](http://a.pomf.se/oqsxyt.png)

**Comment by Nycroth** [comment]
The way the memory script works is that it adds the amount of memory used in buffers and caches to the amount of reported free memory. It does this because the `MemAvailable` readout is relatively new (I believe the Linux kernel introduced it in v3.14). It pulls this info from `/proc/meminfo`. However, all this field really reads is the addition of the buffers, caches, and free memory but calculated at the kernel. The purpose of the memory script is to inform you of the remaining available system memory. If you still believe the script is incorrectly reporting, please feel free to let me know. I just need to know where you're finding the conflict. If you could give me the output of `/proc/meminfo` and the tool with a discrepancy I'll investigate that for you.

For mpc, you don't need to execute the command with a watch (and this will also break the command output for i3blocks due to the ANSI draw outputs). The `interval=20` parameter is exactly equivalent to using a watch in a terminal. When interval is set to 20, every 20 seconds the command will be executed and the result displayed. Now your watch loop was set to 30 so I'm not sure which interval you would prefer but feel free to explore that yourself. Just change `watch -n 30 mpc current` to `mpc current` and the output should show up.

**Comment by Grimmoire** [comment]
Ahhh. My bad. Thanks a ton for the help
